name: C++ CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake protobuf-compiler libprotobuf-dev libfmt-dev
        git clone --depth 1 --branch v1.14.1 https://github.com/onnx/onnx.git
        cd onnx
        git submodule update --init --recursive
        mkdir build && cd build
        cmake -DONNX_USE_PROTOBUF_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release ..
        make -j$(nproc)
        sudo make install

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=Release -B build

    - name: Build
      run: cmake --build ./build