name: C++ CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git wget libprotobuf-dev protobuf-compiler snap libfmt-dev
        sudo snap install cmake --classic
        git clone --recursive https://github.com/onnx/onnx.git ~/onnx
        cd ~/onnx
        # Собираем и устанавливаем
        mkdir -p build && cd build
        cmake .. \
          -DONNX_BUILD_TESTS=OFF \
          -DONNX_USE_PROTOBUF_SHARED_LIBS=ON \
          -DCMAKE_BUILD_TYPE=Release
        make -j$(nproc)
        sudo make install
        sudo ldconfig

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=Release -B build

    - name: Build
      run: cmake --build ./build