name: C++ CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake protobuf-compiler libprotobuf-dev libfmt-dev

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=Release -B build

    - name: Build
      run: cmake --build ./build